name: maqueta
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  provider: ^6.1.2
  image: ^4.3.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6
  pretty_qr_code: ^3.3.0
  http: ^1.2.2
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.2
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2

# ⚙️ Configuración de íconos (Android + iOS)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/Logo_sena_ios.png"
  remove_alpha_ios: true                      # ← AGREGA ESTA LÍNEA (obligatorio para iOS)
  min_sdk_android: 21                         # ← AGREGA ESTA LÍNEA (recomendado)
  
  # Configuración para Android
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/Logo_sena_ios.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/Logo_sena_ios.png